project:
  type: website

website:
  title: "Subhaditya's KB"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

  sidebar: 
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css



