project:
  type: website
  output-dir: docs

website:
  title: "Subhaditya's KB"
  bread-crumbs: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    right:
      - icon: github
        href: https://github.com/

  sidebar: 
    style: docked
    search: true
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css



