site_name: Subhaditya's AI Knowledge Base

theme:
    name: 'material'
    nav_style: dark
    features:
        - toc.follow
        - navigation.top
        - navigation.sections
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.details
  - meta
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.tilde
  - smarty
  - nl2br
  - tables
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - roamlinks 
  - autoreflinks
