---
title: Data Augmentation with Curriculum Learning
categories: ['augment']
date created: Monday, October 10th 2022, 1:58:13 pm
date modified: Monday, October 10th 2022, 2:13:02 pm
---



- @shortenSurveyImageData2019
- [Data Augmentation with Curriculum Learning](Data Augmentation with Curriculum Learning.qmd)

## Methods
- [Geometric Transformations](Geometric%20Transformations.qmd)
- [Flipping](Flipping.qmd)
- [Color Space Transform](Color%20Space%20Transform.qmd)
- [Cropping](Cropping.qmd)
- [Noise Injection](Noise%20Injection.qmd)
- [Color Space Transformations](Color%20Space%20Transformations.qmd)
- [Kernel Filters](Kernel%20Filters.qmd)
- [Feature Space Augmentation](Feature%20Space%20Augmentation.qmd)
- [SMOTE ](SMOTE%20)
- [GAN‐based Data Augmentation](GAN‐based%20Data%20Augmentation.qmd)
- [Meta Learning Data Augmentations](Meta%20Learning%20Data%20Augmentations.qmd)
- [Neural Augmentation](Neural%20Augmentation.qmd)
- [Smart Augmentation](Smart%20Augmentation.qmd)
- [AutoAugment](AutoAugment.qmd)
- [Augmented Random Search](Augmented%20Random%20Search.qmd)
- [Test-time Augmentation](Test-time%20Augmentation.qmd)
- [SamplePairing](SamplePairing.qmd)
- [Data Augmentation with Curriculum Learning](Data%20Augmentation%20with%20Curriculum%20Learning.qmd)
- [Alleviating Class Imbalance with Data Augmentation](Alleviating%20Class%20Imbalance%20with%20Data%20Augmentation.qmd)

## Discussion
- It is easy to explain the benefit of horizontal [Flipping](Flipping.qmd) or random [cropping](cropping.qmd)
- However, it is not clear why mixing pixels or entire images together such as in PatchShuffle [regularization](regularization.qmd) or SamplePairing is so effective.
- dditionally, it is difficult to interpret the representations learned by neural networks for GAN-based augmentation, variational auto-encoders, and meta-learning.
- An interesting characteristic of these augmentation methods is their ability to be combined together.
- The GAN framework possesses an intrinsic property of recursion which is very interesting
- Samples taken from GANs can be augmented with traditional augmentations such as lighting filters, or even used in neural network augmentation strategies such as [Smart Augmentation] or [Neural Augmentation](Smart Augmentation] or [Neural Augmentation.qmd) to create even more samples. These samples can be fed into further GANs and dramatically increase the size of the original dataset.
- An interesting question for practical Data Augmentation is how to determine postaugmented dataset size.
- no consensus about the best strategy for combining data warping and oversampling techniques
- One important consideration is the intrinsic bias in the initial, limited dataset
- There are no existing augmentation techniques that can correct a dataset that has very poor diversity with respect to the testing data



