
---
categories: ['anchor']
---

- [ADVENT.qmd](ADVENT.qmd)
- [ALBERT.qmd](ALBERT.qmd)
- [Adagrad.qmd](Adagrad.qmd)
- [Adaptive Input Representation.qmd](Adaptive%20Input%20Representation.qmd)
- [Additive Attention.qmd](Additive%20Attention.qmd)
- [Affordance Detection Task Specific.qmd](Affordance%20Detection%20Task%20Specific.qmd)
- [Alex Net.qmd](Alex%20Net.qmd)
- [Alphacode.qmd](Alphacode.qmd)
- [Attention NMT.qmd](Attention%20NMT.qmd)
- [Attention.qmd](Attention.qmd)
- [AudioLM.qmd](AudioLM.qmd)
- [Auto Encoders.qmd](Auto%20Encoders.qmd)
- [AutoDistill.qmd](AutoDistill.qmd)
- [BART.qmd](BART.qmd)
- [BERT.qmd](BERT.qmd)
- [Bahdanau Attention.qmd](Bahdanau%20Attention.qmd)
- [Basic GAN.qmd](Basic%20GAN.qmd)
- [Basic RNN Architectures.qmd](Basic%20RNN%20Architectures.qmd)
- [Basic Transformer.qmd](Basic%20Transformer.qmd)
- [Beam search.qmd](Beam%20search.qmd)
- [Bi Directional RNN.qmd](Bi%20Directional%20RNN.qmd)
- [Bias nodes.qmd](Bias%20nodes.qmd)
- [Big Bird.qmd](Big%20Bird.qmd)
- [BinaryBERT.qmd](BinaryBERT.qmd)
- [BlockNeRF.qmd](BlockNeRF.qmd)
- [CLIP.qmd](CLIP.qmd)
- [Capsule Layer.qmd](Capsule%20Layer.qmd)
- [Capsule Network.qmd](Capsule%20Network.qmd)
- [Chat GPT is Not All You Need.qmd](Chat%20GPT%20is%20Not%20All%20You%20Need.qmd)
- [ChatGPT.qmd](ChatGPT.qmd)
- [Chinchilla.qmd](Chinchilla.qmd)
- [Classifier Gradients.qmd](Classifier%20Gradients.qmd)
- [Codex.qmd](Codex.qmd)
- [Collaborative Topic Regression.qmd](Collaborative%20Topic%20Regression.qmd)
- [Conditional GAN.qmd](Conditional%20GAN.qmd)
- [Conformer.qmd](Conformer.qmd)
- [Content Based Attention.qmd](Content%20Based%20Attention.qmd)
- [Contrastive Predictive Coding.qmd](Contrastive%20Predictive%20Coding.qmd)
- [ConvBERT.qmd](ConvBERT.qmd)
- [ConvNeXt.qmd](ConvNeXt.qmd)
- [Convolutional RNN.qmd](Convolutional%20RNN.qmd)
- [Curriculum Learning.qmd](Curriculum%20Learning.qmd)
- [CycleGAN.qmd](CycleGAN.qmd)
- [DALL-E 3.qmd](DALL-E%203.qmd)
- [DALL-E.qmd](DALL-E.qmd)
- [DALL·E 2.qmd](DALL·E%202.qmd)
- [DCGAN.qmd](DCGAN.qmd)
- [DLRM.qmd](DLRM.qmd)
- [DeepFM.qmd](DeepFM.qmd)
- [DeepNet.qmd](DeepNet.qmd)
- [DeepPERF.qmd](DeepPERF.qmd)
- [Denoising Autoencoder.qmd](Denoising%20Autoencoder.qmd)
- [Dense Net.qmd](Dense%20Net.qmd)
- [Diffusion LM.qmd](Diffusion%20LM.qmd)
- [Dilated Sliding Window Attention.qmd](Dilated%20Sliding%20Window%20Attention.qmd)
- [DistillBERT.qmd](DistillBERT.qmd)
- [Dot Product Attention.qmd](Dot%20Product%20Attention.qmd)
- [Dreamfusion.qmd](Dreamfusion.qmd)
- [Dynamic Sparsity.qmd](Dynamic%20Sparsity.qmd)
- [ELECTRA.qmd](ELECTRA.qmd)
- [ELMO.qmd](ELMO.qmd)
- [EfficientNet.qmd](EfficientNet.qmd)
- [Elu.qmd](Elu.qmd)
- [Encoder Decoder Attention.qmd](Encoder%20Decoder%20Attention.qmd)
- [Ensemble Distillation.qmd](Ensemble%20Distillation.qmd)
- [FLASH.qmd](FLASH.qmd)
- [FLAVA.qmd](FLAVA.qmd)
- [FaceNet.qmd](FaceNet.qmd)
- [Factorized Embedding Parameters.qmd](Factorized%20Embedding%20Parameters.qmd)
- [Familar Object Grasping Object Viiew recog.qmd](Familar%20Object%20Grasping%20Object%20Viiew%20recog.qmd)
- [FastText.qmd](FastText.qmd)
- [Faster RCNN.qmd](Faster%20RCNN.qmd)
- [Feature Correlationa.qmd](Feature%20Correlationa.qmd)
- [Fixed Factorization Attention.qmd](Fixed%20Factorization%20Attention.qmd)
- [Flamingo.qmd](Flamingo.qmd)
- [FlowNet.qmd](FlowNet.qmd)
- [GAN Z Space.qmd](GAN%20Z%20Space.qmd)
- [GAU.qmd](GAU.qmd)
- [GELU.qmd](GELU.qmd)
- [GGCNN.qmd](GGCNN.qmd)
- [GLOW.qmd](GLOW.qmd)
- [GPT.qmd](GPT.qmd)
- [GPT3.qmd](GPT3.qmd)
- [GRConvNet.qmd](GRConvNet.qmd)
- [GRU.qmd](GRU.qmd)
- [Galactica.qmd](Galactica.qmd)
- [Gato.qmd](Gato.qmd)
- [Generative Models.qmd](Generative%20Models.qmd)
- [Generative RNN.qmd](Generative%20RNN.qmd)
- [Generative Spoken Language Modeling.qmd](Generative%20Spoken%20Language%20Modeling.qmd)
- [Generative vs Discriminative Models.qmd](Generative%20vs%20Discriminative%20Models.qmd)
- [GloVE.qmd](GloVE.qmd)
- [Global Average Pooling.qmd](Global%20Average%20Pooling.qmd)
- [Global and Sliding Window Attention.qmd](Global%20and%20Sliding%20Window%20Attention.qmd)
- [Google NMT.qmd](Google%20NMT.qmd)
- [Grad-CAM.qmd](Grad-CAM.qmd)
- [Hallucination Text Generation.qmd](Hallucination%20Text%20Generation.qmd)
- [HiFI-GAN Denoising.qmd](HiFI-GAN%20Denoising.qmd)
- [HiFI-GAN Synthesis.qmd](HiFI-GAN%20Synthesis.qmd)
- [Higher Layer Capsule.qmd](Higher%20Layer%20Capsule.qmd)
- [Highway Convolutions.qmd](Highway%20Convolutions.qmd)
- [Hopfield networks.qmd](Hopfield%20networks.qmd)
- [Imagen.qmd](Imagen.qmd)
- [Inception.qmd](Inception.qmd)
- [Instance Normalization.qmd](Instance%20Normalization.qmd)
- [Instant NeRF.qmd](Instant%20NeRF.qmd)
- [Interpreting Attention.qmd](Interpreting%20Attention.qmd)
- [Isotropic Architectures.qmd](Isotropic%20Architectures.qmd)
- [Joint Factor Analysis.qmd](Joint%20Factor%20Analysis.qmd)
- [Jukebox.qmd](Jukebox.qmd)
- [LASER.qmd](LASER.qmd)
- [LaMDA.qmd](LaMDA.qmd)
- [Large Kernel in Attention.qmd](Large%20Kernel%20in%20Attention.qmd)
- [Large Kernel in Convolution.qmd](Large%20Kernel%20in%20Convolution.qmd)
- [Le Net.qmd](Le%20Net.qmd)
- [Learning to Detect Grasp Affordance.qmd](Learning%20to%20Detect%20Grasp%20Affordance.qmd)
- [Linear Classifier Probes.qmd](Linear%20Classifier%20Probes.qmd)
- [Listen Attend Spell.qmd](Listen%20Attend%20Spell.qmd)
- [Location Aware Attention.qmd](Location%20Aware%20Attention.qmd)
- [Location Base Attention.qmd](Location%20Base%20Attention.qmd)
- [Long Short Term Memory (LSTM).qmd](Long%20Short%20Term%20Memory%20(LSTM).qmd)
- [Longformer.qmd](Longformer.qmd)
- [MCnet.qmd](MCnet.qmd)
- [MLIM.qmd](MLIM.qmd)
- [MLM.qmd](MLM.qmd)
- [MVGrasp.qmd](MVGrasp.qmd)
- [Magic3D.qmd](Magic3D.qmd)
- [Masked Autoencoders.qmd](Masked%20Autoencoders.qmd)
- [Minerva.qmd](Minerva.qmd)
- [Mixed chunk attention.qmd](Mixed%20chunk%20attention.qmd)
- [Mobile Net.qmd](Mobile%20Net.qmd)
- [MobileOne.qmd](MobileOne.qmd)
- [Multi Head Attention.qmd](Multi%20Head%20Attention.qmd)
- [Multiplicative Attention.qmd](Multiplicative%20Attention.qmd)
- [Muse.qmd](Muse.qmd)
- [Nasnet.qmd](Nasnet.qmd)
- [Neural Network Architecture Cheat Sheet.qmd](Neural%20Network%20Architecture%20Cheat%20Sheet.qmd)
- [Neural Probabilistic Model.qmd](Neural%20Probabilistic%20Model.qmd)
- [Neural Text Degeneration.qmd](Neural%20Text%20Degeneration.qmd)
- [Noisy Relu.qmd](Noisy%20Relu.qmd)
- [OPT.qmd](OPT.qmd)
- [PEER.qmd](PEER.qmd)
- [PRelu.qmd](PRelu.qmd)
- [PaLM.qmd](PaLM.qmd)
- [Padded Conv.qmd](Padded%20Conv.qmd)
- [PatchGAN.qmd](PatchGAN.qmd)
- [Phenaki.qmd](Phenaki.qmd)
- [Phrase Representation Learning.qmd](Phrase%20Representation%20Learning.qmd)
- [Pix2Seq.qmd](Pix2Seq.qmd)
- [Point Cloud.qmd](Point%20Cloud.qmd)
- [PointNet++.qmd](PointNet++.qmd)
- [Position Encoding.qmd](Position%20Encoding.qmd)
- [Position Wise Feed Forward.qmd](Position%20Wise%20Feed%20Forward.qmd)
- [Primary Capsule.qmd](Primary%20Capsule.qmd)
- [RETRO.qmd](RETRO.qmd)
- [Receptive field.qmd](Receptive%20field.qmd)
- [RegNet.qmd](RegNet.qmd)
- [Region Proposal.qmd](Region%20Proposal.qmd)
- [Relative Multi Head Self Attention.qmd](Relative%20Multi%20Head%20Self%20Attention.qmd)
- [Relu.qmd](Relu.qmd)
- [RepLKNet.qmd](RepLKNet.qmd)
- [Res Net D.qmd](Res%20Net%20D.qmd)
- [Res Net.qmd](Res%20Net.qmd)
- [Restricted Boltzmann Machine.qmd](Restricted%20Boltzmann%20Machine.qmd)
- [RetinaNet.qmd](RetinaNet.qmd)
- [Rmsprop.qmd](Rmsprop.qmd)
- [RoBERTa.qmd](RoBERTa.qmd)
- [Routing by Agreement.qmd](Routing%20by%20Agreement.qmd)
- [S2ST.qmd](S2ST.qmd)
- [SLAK.qmd](SLAK.qmd)
- [SRN.qmd](SRN.qmd)
- [Scaled Dot Product Attention.qmd](Scaled%20Dot%20Product%20Attention.qmd)
- [Scene based text to image generation.qmd](Scene%20based%20text%20to%20image%20generation.qmd)
- [SegNet.qmd](SegNet.qmd)
- [Self Attention GAN.qmd](Self%20Attention%20GAN.qmd)
- [Self Attention.qmd](Self%20Attention.qmd)
- [Seq2Seq.qmd](Seq2Seq.qmd)
- [ShuffleNet.qmd](ShuffleNet.qmd)
- [Sigmoid.qmd](Sigmoid.qmd)
- [Sliding Window Attention.qmd](Sliding%20Window%20Attention.qmd)
- [Soft Attention.qmd](Soft%20Attention.qmd)
- [Softmax.qmd](Softmax.qmd)
- [Softplus.qmd](Softplus.qmd)
- [Soundify.qmd](Soundify.qmd)
- [Sparse Evolutionary Training.qmd](Sparse%20Evolutionary%20Training.qmd)
- [Sparse Transformer.qmd](Sparse%20Transformer.qmd)
- [Spatial Transformer.qmd](Spatial%20Transformer.qmd)
- [Speaker Verification.qmd](Speaker%20Verification.qmd)
- [Speech Emotion Recognition.qmd](Speech%20Emotion%20Recognition.qmd)
- [Speech Recognition.qmd](Speech%20Recognition.qmd)
- [Speech Resynthesis.qmd](Speech%20Resynthesis.qmd)
- [Spiking Networks.qmd](Spiking%20Networks.qmd)
- [Stable Difusion.qmd](Stable%20Difusion.qmd)
- [Stack GAN.qmd](Stack%20GAN.qmd)
- [Stacking RNN.qmd](Stacking%20RNN.qmd)
- [StarGAN v2.qmd](StarGAN%20v2.qmd)
- [StarGAN.qmd](StarGAN.qmd)
- [Strided Attention.qmd](Strided%20Attention.qmd)
- [Strided.qmd](Strided.qmd)
- [Style GAN.qmd](Style%20GAN.qmd)
- [Swish.qmd](Swish.qmd)
- [TSDF.qmd](TSDF.qmd)
- [Tacotron.qmd](Tacotron.qmd)
- [Tanh.qmd](Tanh.qmd)
- [Teacher Forcing.qmd](Teacher%20Forcing.qmd)
- [Temporal Conv.qmd](Temporal%20Conv.qmd)
- [TemporalLearning.qmd](TemporalLearning.qmd)
- [Textless Speech Emotion Conversion.qmd](Textless%20Speech%20Emotion%20Conversion.qmd)
- [TinyBERT.qmd](TinyBERT.qmd)
- [Token Embedding.qmd](Token%20Embedding.qmd)
- [Transformer-XL.qmd](Transformer-XL.qmd)
- [Transformer.qmd](Transformer.qmd)
- [Transposed Conv.qmd](Transposed%20Conv.qmd)
- [ULMFit.qmd](ULMFit.qmd)
- [Un-LSTM.qmd](Un-LSTM.qmd)
- [Unet Grasping.qmd](Unet%20Grasping.qmd)
- [Unet.qmd](Unet.qmd)
- [VAE.qmd](VAE.qmd)
- [VGGish.qmd](VGGish.qmd)
- [VICReg.qmd](VICReg.qmd)
- [VL-BEIT.qmd](VL-BEIT.qmd)
- [Vgg.qmd](Vgg.qmd)
- [ViLT.qmd](ViLT.qmd)
- [VisualGPT.qmd](VisualGPT.qmd)
- [Volumetric Grasping Network.qmd](Volumetric%20Grasping%20Network.qmd)
- [WaveGlow.qmd](WaveGlow.qmd)
- [WebGPT.qmd](WebGPT.qmd)
- [Whisper.qmd](Whisper.qmd)
- [Wide Deep Recommender.qmd](Wide%20Deep%20Recommender.qmd)
- [Window Based Regression.qmd](Window%20Based%20Regression.qmd)
- [Word2Vec.qmd](Word2Vec.qmd)
- [X Vectors.qmd](X%20Vectors.qmd)
- [XLM-R.qmd](XLM-R.qmd)
- [XLNet.qmd](XLNet.qmd)
- [Xception.qmd](Xception.qmd)
- [YOLO.qmd](YOLO.qmd)
- [Z-Space Entanglement.qmd](Z-Space%20Entanglement.qmd)
- [Zeiler Fergus.qmd](Zeiler%20Fergus.qmd)
- [cross-layer parameter sharing.qmd](cross-layer%20parameter%20sharing.qmd)
- [dGSLM.qmd](dGSLM.qmd)
- [data2vec.qmd](data2vec.qmd)
- [i-Code.qmd](i-Code.qmd)
- [pGLSM.qmd](pGLSM.qmd)
- [wave2vec.qmd](wave2vec.qmd)
