
---
categories: ['anchor']
---

- [ACT-R Chunk.qmd](ACT-R%20Chunk.qmd)
- [ACT-R.qmd](ACT-R.qmd)
- [Active tracking.qmd](Active%20tracking.qmd)
- [CogMod Final Paper.qmd](CogMod%20Final%20Paper.qmd)
- [Cognition Hazard Rates.qmd](Cognition%20Hazard%20Rates.qmd)
- [Cognitive Foreperiod.qmd](Cognitive%20Foreperiod.qmd)
- [Cognitive Multitasking.qmd](Cognitive%20Multitasking.qmd)
- [Cognitive Preparation.qmd](Cognitive%20Preparation.qmd)
- [Cognitive fMTP.qmd](Cognitive%20fMTP.qmd)
- [Declarative Memory Blending.qmd](Declarative%20Memory%20Blending.qmd)
- [Declarative memory.qmd](Declarative%20memory.qmd)
- [Dikes and Rivers.qmd](Dikes%20and%20Rivers.qmd)
- [Implicitly learning when to be ready - From instances to categories.qmd](Implicitly%20learning%20when%20to%20be%20ready%20-%20From%20instances%20to%20categories.qmd)
- [Mental Fatigue.qmd](Mental%20Fatigue.qmd)
- [Modeling Driver Behavior with Cognitive Architecture.qmd](Modeling%20Driver%20Behavior%20with%20Cognitive%20Architecture.qmd)
- [Modeling motivation using goal competition in mental fatigue studies.qmd](Modeling%20motivation%20using%20goal%20competition%20in%20mental%20fatigue%20studies.qmd)
- [On the Distinction Between Perceived Duration and Event Timing - Towards a Unified Model of Time Perception.qmd](On%20the%20Distinction%20Between%20Perceived%20Duration%20and%20Event%20Timing%20-%20Towards%20a%20Unified%20Model%20of%20Time%20Perception.qmd)
- [Revisiting variable foreperiod effects evaluating the repetition priming account.qmd](Revisiting%20variable%20foreperiod%20effects%20evaluating%20the%20repetition%20priming%20account.qmd)
- [Scaled benefits.qmd](Scaled%20benefits.qmd)
- [Sequential effects within a short foreperiod context Evidence for the conditioning account of temporal preparation.qmd](Sequential%20effects%20within%20a%20short%20foreperiod%20context%20Evidence%20for%20the%20conditioning%20account%20of%20temporal%20preparation.qmd)
- [Sugar Factory Task.qmd](Sugar%20Factory%20Task.qmd)
- [The Reward Experiment.qmd](The%20Reward%20Experiment.qmd)
- [The warning stimulus as retrieval cue The role of associative memory in temporal preparation.qmd](The%20warning%20stimulus%20as%20retrieval%20cue%20The%20role%20of%20associative%20memory%20in%20temporal%20preparation.qmd)
- [Threaded Cognition.qmd](Threaded%20Cognition.qmd)
- [Traces of times past Representations of temporal intervals in memory.qmd](Traces%20of%20times%20past%20Representations%20of%20temporal%20intervals%20in%20memory.qmd)
- [You can play 20 questions with nature and win.qmd](You%20can%20play%2020%20questions%20with%20nature%20and%20win.qmd)
