
---
categories: ['anchor']
---

- [A declarative modular framework for representing and applying ethical principles.qmd](A%20declarative%20modular%20framework%20for%20representing%20and%20applying%20ethical%20principles.qmd)
- [A low-cost ethics shaping approach for designing reinforcement learning agents.qmd](A%20low-cost%20ethics%20shaping%20approach%20for%20designing%20reinforcement%20learning%20agents.qmd)
- [A voting-based system for ethical decision making.qmd](A%20voting-based%20system%20for%20ethical%20decision%20making.qmd)
- [Belief-Desire-Intention.qmd](Belief-Desire-Intention.qmd)
- [Building Ethics into Artificial Intelligence.qmd](Building%20Ethics%20into%20Artificial%20Intelligence.qmd)
- [Capture bias.qmd](Capture%20bias.qmd)
- [Collective Ethical Decision Frameworks.qmd](Collective%20Ethical%20Decision%20Frameworks.qmd)
- [Consequentialist ethics.qmd](Consequentialist%20ethics.qmd)
- [Coping Theory.qmd](Coping%20Theory.qmd)
- [Coverage of ethics within the artificial intelligence and machine learning academic literature.qmd](Coverage%20of%20ethics%20within%20the%20artificial%20intelligence%20and%20machine%20learning%20academic%20literature.qmd)
- [Cross-dataset generalization.qmd](Cross-dataset%20generalization.qmd)
- [Deontological ethics.qmd](Deontological%20ethics.qmd)
- [Embedding ethical principles in collective decision support systems.qmd](Embedding%20ethical%20principles%20in%20collective%20decision%20support%20systems.qmd)
- [Ethical dilemmas.qmd](Ethical%20dilemmas.qmd)
- [Even angels need the rules AI, roboethics, and the law.qmd](Even%20angels%20need%20the%20rules%20AI,%20roboethics,%20and%20the%20law.qmd)
- [GenEth.qmd](GenEth.qmd)
- [Label bias.qmd](Label%20bias.qmd)
- [Moral Machine project.qmd](Moral%20Machine%20project.qmd)
- [Moral decision making frameworks for artificial intelligence.qmd](Moral%20decision%20making%20frameworks%20for%20artificial%20intelligence.qmd)
- [MoralDM.qmd](MoralDM.qmd)
- [Negative Set Bias.qmd](Negative%20Set%20Bias.qmd)
- [Norms as a basis for governing sociotechnical systems.qmd](Norms%20as%20a%20basis%20for%20governing%20sociotechnical%20systems.qmd)
- [Preferences and ethical principles in decision making.qmd](Preferences%20and%20ethical%20principles%20in%20decision%20making.qmd)
- [Selection Bias.qmd](Selection%20Bias.qmd)
- [Unbiased Look at Dataset Bias.qmd](Unbiased%20Look%20at%20Dataset%20Bias.qmd)
- [Utilitarian ethics.qmd](Utilitarian%20ethics.qmd)
- [Virtue ethics.qmd](Virtue%20ethics.qmd)
- [blind ethical judgement.qmd](blind%20ethical%20judgement.qmd)
- [fully informed ethical judgement.qmd](fully%20informed%20ethical%20judgement.qmd)
- [partially informed ethical judgement.qmd](partially%20informed%20ethical%20judgement.qmd)
- [sacred values.qmd](sacred%20values.qmd)
- [swap-dominance.qmd](swap-dominance.qmd)
- [trolley scenario.qmd](trolley%20scenario.qmd)
