
---
categories: ['anchor']
---

- [2 X 2 Study.qmd](2%20X%202%20Study.qmd)
- [2 byte character set.qmd](2%20byte%20character%20set.qmd)
- [8 bit character set.qmd](8%20bit%20character%20set.qmd)
- [A matter of ambiguity? Using eye movements to examine collective vs distributive interpretations of plural sets.qmd](A%20matter%20of%20ambiguity?%20Using%20eye%20movements%20to%20examine%20collective%20vs%20distributive%20interpretations%20of%20plural%20sets.qmd)
- [ANOVA.qmd](ANOVA.qmd)
- [ASCII.qmd](ASCII.qmd)
- [Action Transitive verb.qmd](Action%20Transitive%20verb.qmd)
- [Adjective.qmd](Adjective.qmd)
- [Adverb.qmd](Adverb.qmd)
- [Agglutinating words.qmd](Agglutinating%20words.qmd)
- [Allomorph.qmd](Allomorph.qmd)
- [Application dependence.qmd](Application%20dependence.qmd)
- [Approximately Compositional Semantic Parsing.qmd](Approximately%20Compositional%20Semantic%20Parsing.qmd)
- [Attentions and salience.qmd](Attentions%20and%20salience.qmd)
- [Berkeley et al.qmd](Berkeley%20et%20al.qmd)
- [Bottom Up Parsing.qmd](Bottom%20Up%20Parsing.qmd)
- [Bound morpheme.qmd](Bound%20morpheme.qmd)
- [Cardinality Principle.qmd](Cardinality%20Principle.qmd)
- [Case Grammar.qmd](Case%20Grammar.qmd)
- [Challenges of Words-and-rules.qmd](Challenges%20of%20Words-and-rules.qmd)
- [Character-set dependence.qmd](Character-set%20dependence.qmd)
- [Circumfix.qmd](Circumfix.qmd)
- [Collective Interpretation.qmd](Collective%20Interpretation.qmd)
- [Collectivity, Distributivity, and the Interpretation of Plural Numerical Expressions in Child and Adult Language.qmd](Collectivity,%20Distributivity,%20and%20the%20Interpretation%20of%20Plural%20Numerical%20Expressions%20in%20Child%20and%20Adult%20Language.qmd)
- [Conceptual Parsing.qmd](Conceptual%20Parsing.qmd)
- [Connectionism.qmd](Connectionism.qmd)
- [Connectionist Networks.qmd](Connectionist%20Networks.qmd)
- [Connectives.qmd](Connectives.qmd)
- [Content Morpheme.qmd](Content%20Morpheme.qmd)
- [Content words.qmd](Content%20words.qmd)
- [Context Free Grammar.qmd](Context%20Free%20Grammar.qmd)
- [Corpus dependence.qmd](Corpus%20dependence.qmd)
- [Cross-situational learning.qmd](Cross-situational%20learning.qmd)
- [Cumulative Interpretation.qmd](Cumulative%20Interpretation.qmd)
- [Deductive Approaches.qmd](Deductive%20Approaches.qmd)
- [Derivational Morphology.qmd](Derivational%20Morphology.qmd)
- [Determiners.qmd](Determiners.qmd)
- [DiTransitive verb.qmd](DiTransitive%20verb.qmd)
- [Distributive Interpretation (2).qmd](Distributive%20Interpretation%20(2).qmd)
- [Distributive Interpretation.qmd](Distributive%20Interpretation.qmd)
- [Distributive units.qmd](Distributive%20units.qmd)
- [Document Triage.qmd](Document%20Triage.qmd)
- [Elements of sets.qmd](Elements%20of%20sets.qmd)
- [Elman 1990.qmd](Elman%201990.qmd)
- [Elman 1991.qmd](Elman%201991.qmd)
- [Elman 1992.qmd](Elman%201992.qmd)
- [Elman 1993.qmd](Elman%201993.qmd)
- [Emergentism.qmd](Emergentism.qmd)
- [Entities involving in actions.qmd](Entities%20involving%20in%20actions.qmd)
- [Evidence For Distributivity Effects in Comprehension.qmd](Evidence%20For%20Distributivity%20Effects%20in%20Comprehension.qmd)
- [Extra-position.qmd](Extra-position.qmd)
- [Final Paper Language Modeling.qmd](Final%20Paper%20Language%20Modeling.qmd)
- [First order generalization.qmd](First%20order%20generalization.qmd)
- [Fixed Factors.qmd](Fixed%20Factors.qmd)
- [Forward Backward Matching.qmd](Forward%20Backward%20Matching.qmd)
- [Free morpheme.qmd](Free%20morpheme.qmd)
- [Function words.qmd](Function%20words.qmd)
- [Functional Morpheme.qmd](Functional%20Morpheme.qmd)
- [Hybrid Word Segmentation.qmd](Hybrid%20Word%20Segmentation.qmd)
- [Inductive Learning.qmd](Inductive%20Learning.qmd)
- [Infix.qmd](Infix.qmd)
- [Inflectional Morphology.qmd](Inflectional%20Morphology.qmd)
- [Inflectional words.qmd](Inflectional%20words.qmd)
- [Isolating words.qmd](Isolating%20words.qmd)
- [Language Identification.qmd](Language%20Identification.qmd)
- [Language dependence.qmd](Language%20dependence.qmd)
- [Latent Dirchlet Allocation.qmd](Latent%20Dirchlet%20Allocation.qmd)
- [Lemmatization.qmd](Lemmatization.qmd)
- [Lexical Ambiguity.qmd](Lexical%20Ambiguity.qmd)
- [Lexical Disambiguation.qmd](Lexical%20Disambiguation.qmd)
- [Lexical Word Segmentation.qmd](Lexical%20Word%20Segmentation.qmd)
- [Lexically Collective.qmd](Lexically%20Collective.qmd)
- [Lexically Distributive.qmd](Lexically%20Distributive.qmd)
- [Lexicon.qmd](Lexicon.qmd)
- [Linguistic details.qmd](Linguistic%20details.qmd)
- [Localist units.qmd](Localist%20units.qmd)
- [Maximum Matching Algorithm.qmd](Maximum%20Matching%20Algorithm.qmd)
- [Memory-based learning.qmd](Memory-based%20learning.qmd)
- [Milin et al.qmd](Milin%20et%20al.qmd)
- [Minimal Semantic Commitment.qmd](Minimal%20Semantic%20Commitment.qmd)
- [Mirman et al.qmd](Mirman%20et%20al.qmd)
- [Misyak et al 2010.qmd](Misyak%20et%20al%202010.qmd)
- [Mixed Effect Models.qmd](Mixed%20Effect%20Models.qmd)
- [Morpheme Generation.qmd](Morpheme%20Generation.qmd)
- [Morpheme Segmentation.qmd](Morpheme%20Segmentation.qmd)
- [Morpheme.qmd](Morpheme.qmd)
- [Morphology Affix.qmd](Morphology%20Affix.qmd)
- [Morphology Stem.qmd](Morphology%20Stem.qmd)
- [Morphology.qmd](Morphology.qmd)
- [Morphotactic.qmd](Morphotactic.qmd)
- [Multiple constraint-based theories.qmd](Multiple%20constraint-based%20theories.qmd)
- [Names of individuals.qmd](Names%20of%20individuals.qmd)
- [Nativists.qmd](Nativists.qmd)
- [Non-adjacent dependencies.qmd](Non-adjacent%20dependencies.qmd)
- [Numerically Quantified Expressions.qmd](Numerically%20Quantified%20Expressions.qmd)
- [Object-relative clauses.qmd](Object-relative%20clauses.qmd)
- [Ostension.qmd](Ostension.qmd)
- [Ostensive Information.qmd](Ostensive%20Information.qmd)
- [Overhypotheses.qmd](Overhypotheses.qmd)
- [Parts of action.qmd](Parts%20of%20action.qmd)
- [Parts of entities.qmd](Parts%20of%20entities.qmd)
- [Phonetics.qmd](Phonetics.qmd)
- [Phonology.qmd](Phonology.qmd)
- [Picky Puppet Method.qmd](Picky%20Puppet%20Method.qmd)
- [Polysynthetic words.qmd](Polysynthetic%20words.qmd)
- [Pragmatics.qmd](Pragmatics.qmd)
- [Predicate.qmd](Predicate.qmd)
- [Prefix.qmd](Prefix.qmd)
- [Prepositions.qmd](Prepositions.qmd)
- [Propose-but-verify.qmd](Propose-but-verify.qmd)
- [Psycholinguistics.qmd](Psycholinguistics.qmd)
- [Punctuation.qmd](Punctuation.qmd)
- [Quantifier spreading children misled by ostensive cues.qmd](Quantifier%20spreading%20children%20misled%20by%20ostensive%20cues.qmd)
- [Quantifiers.qmd](Quantifiers.qmd)
- [Random Factors.qmd](Random%20Factors.qmd)
- [Relevance Account.qmd](Relevance%20Account.qmd)
- [Relevance Theory.qmd](Relevance%20Theory.qmd)
- [Rescorla-Wagner Algorithm.qmd](Rescorla-Wagner%20Algorithm.qmd)
- [Rescorla-Wagner Blocking.qmd](Rescorla-Wagner%20Blocking.qmd)
- [Saffran, Aslin and Newport.qmd](Saffran,%20Aslin%20and%20Newport.qmd)
- [Salient Object Strategy.qmd](Salient%20Object%20Strategy.qmd)
- [Second order generalization.qmd](Second%20order%20generalization.qmd)
- [Semantic Analysis.qmd](Semantic%20Analysis.qmd)
- [Semantic Grammar.qmd](Semantic%20Grammar.qmd)
- [Semantic Markers.qmd](Semantic%20Markers.qmd)
- [Semantics influences form.qmd](Semantics%20influences%20form.qmd)
- [Sentence Segmentation.qmd](Sentence%20Segmentation.qmd)
- [Sentence level processing.qmd](Sentence%20level%20processing.qmd)
- [Shared Character Set.qmd](Shared%20Character%20Set.qmd)
- [Shortcuts to Quantifier Interpretation in Children and Adults.qmd](Shortcuts%20to%20Quantifier%20Interpretation%20in%20Children%20and%20Adults.qmd)
- [Single unit recording.qmd](Single%20unit%20recording.qmd)
- [Statistical Word Segmentation.qmd](Statistical%20Word%20Segmentation.qmd)
- [Subject relative.qmd](Subject%20relative.qmd)
- [Subject-verb agreement.qmd](Subject-verb%20agreement.qmd)
- [Suffix.qmd](Suffix.qmd)
- [Superposition Catastrophe.qmd](Superposition%20Catastrophe.qmd)
- [Suppletion.qmd](Suppletion.qmd)
- [Symbolic learning model.qmd](Symbolic%20learning%20model.qmd)
- [Symbolic models.qmd](Symbolic%20models.qmd)
- [Syntactic Ambiguity.qmd](Syntactic%20Ambiguity.qmd)
- [Syntactic Analysis.qmd](Syntactic%20Analysis.qmd)
- [Syntactic Bootstrapping.qmd](Syntactic%20Bootstrapping.qmd)
- [Syntax First models.qmd](Syntax%20First%20models.qmd)
- [Taking on semantic commitments, II collective versus distributive readings.qmd](Taking%20on%20semantic%20commitments,%20II%20collective%20versus%20distributive%20readings.qmd)
- [Text Normalization.qmd](Text%20Normalization.qmd)
- [Text Preprocessing.qmd](Text%20Preprocessing.qmd)
- [Text Segmentation.qmd](Text%20Segmentation.qmd)
- [The Differentiation Condition.qmd](The%20Differentiation%20Condition.qmd)
- [The Self Organization of Explicit Attitudes.qmd](The%20Self%20Organization%20of%20Explicit%20Attitudes.qmd)
- [Tokenizer.qmd](Tokenizer.qmd)
- [Top Down Parsing.qmd](Top%20Down%20Parsing.qmd)
- [Tracking the Continuity of Language Comprehension Computer Mouse Trajectories Suggest Parallel Syntactic Processing.qmd](Tracking%20the%20Continuity%20of%20Language%20Comprehension%20Computer%20Mouse%20Trajectories%20Suggest%20Parallel%20Syntactic%20Processing.qmd)
- [Transitional probabilities.qmd](Transitional%20probabilities.qmd)
- [Transitive verb.qmd](Transitive%20verb.qmd)
- [Types of Words.qmd](Types%20of%20Words.qmd)
- [Unicode 50.qmd](Unicode%2050.qmd)
- [Unique Character Set.qmd](Unique%20Character%20Set.qmd)
- [Universal Quantifiers.qmd](Universal%20Quantifiers.qmd)
- [Unrestricted Race Model.qmd](Unrestricted%20Race%20Model.qmd)
- [Verb.qmd](Verb.qmd)
- [Visual Implicit Learning.qmd](Visual%20Implicit%20Learning.qmd)
- [Wh-dependencies.qmd](Wh-dependencies.qmd)
- [Wickelphones.qmd](Wickelphones.qmd)
- [Word Blending.qmd](Word%20Blending.qmd)
- [Word Clipping.qmd](Word%20Clipping.qmd)
- [Word Compounding.qmd](Word%20Compounding.qmd)
- [Word Segmentation.qmd](Word%20Segmentation.qmd)
- [Word Structure.qmd](Word%20Structure.qmd)
- [Words-and-Rules.qmd](Words-and-Rules.qmd)
- [conditioning.qmd](conditioning.qmd)
- [past tense.qmd](past%20tense.qmd)
