
---
categories: ['anchor']
---

- [Attentions and salience.qmd](Attentions%20and%20salience.qmd)
- [Berkeley et al.qmd](Berkeley%20et%20al.qmd)
- [Challenges of Words-and-rules.qmd](Challenges%20of%20Words-and-rules.qmd)
- [Connectionism.qmd](Connectionism.qmd)
- [Connectionist Networks.qmd](Connectionist%20Networks.qmd)
- [Cross-situational learning.qmd](Cross-situational%20learning.qmd)
- [Deductive Approaches.qmd](Deductive%20Approaches.qmd)
- [Distributive units.qmd](Distributive%20units.qmd)
- [Elman 1990.qmd](Elman%201990.qmd)
- [Elman 1991.qmd](Elman%201991.qmd)
- [Elman 1992.qmd](Elman%201992.qmd)
- [Elman 1993.qmd](Elman%201993.qmd)
- [Emergentism.qmd](Emergentism.qmd)
- [Extra-position.qmd](Extra-position.qmd)
- [First order generalization.qmd](First%20order%20generalization.qmd)
- [Inductive Learning.qmd](Inductive%20Learning.qmd)
- [Localist units.qmd](Localist%20units.qmd)
- [Memory-based learning.qmd](Memory-based%20learning.qmd)
- [Milin et al.qmd](Milin%20et%20al.qmd)
- [Mirman et al.qmd](Mirman%20et%20al.qmd)
- [Misyak et al 2010.qmd](Misyak%20et%20al%202010.qmd)
- [Nativists.qmd](Nativists.qmd)
- [Non-adjacent dependencies.qmd](Non-adjacent%20dependencies.qmd)
- [Object-relative clauses.qmd](Object-relative%20clauses.qmd)
- [Overhypotheses.qmd](Overhypotheses.qmd)
- [Propose-but-verify.qmd](Propose-but-verify.qmd)
- [Rescorla-Wagner Algorithm.qmd](Rescorla-Wagner%20Algorithm.qmd)
- [Rescorla-Wagner Blocking.qmd](Rescorla-Wagner%20Blocking.qmd)
- [Saffran, Aslin and Newport.qmd](Saffran,%20Aslin%20and%20Newport.qmd)
- [Second order generalization.qmd](Second%20order%20generalization.qmd)
- [Semantics influences form.qmd](Semantics%20influences%20form.qmd)
- [Single unit recording.qmd](Single%20unit%20recording.qmd)
- [Subject relative.qmd](Subject%20relative.qmd)
- [Subject-verb agreement.qmd](Subject-verb%20agreement.qmd)
- [Superposition Catastrophe.qmd](Superposition%20Catastrophe.qmd)
- [Symbolic learning model.qmd](Symbolic%20learning%20model.qmd)
- [Symbolic models.qmd](Symbolic%20models.qmd)
- [Transitional probabilities.qmd](Transitional%20probabilities.qmd)
- [Visual Implicit Learning.qmd](Visual%20Implicit%20Learning.qmd)
- [Wh-dependencies.qmd](Wh-dependencies.qmd)
- [Wickelphones.qmd](Wickelphones.qmd)
- [Words-and-Rules.qmd](Words-and-Rules.qmd)
- [conditioning.qmd](conditioning.qmd)
