---
categories: ['temp']
date modified: Monday, October 10th 2022, 2:02:30 pm
date created: Tuesday, July 26th 2022, 8:33:15 pm
---

---

toc: true
title: CvT

categories: ['temp']

---

# CvT
- [CvT: Introducing Convolutions to Vision Transformers](https://arxiv.org/abs/2103.15808)
	- improves [Vision Transformer](Vision%20Transformer.qmd)
	- introducing [Conv](Conv.qmd)
	- a hierarchy of Transformers containing a new convolutional token [Embedding](Embedding.qmd)
	- convolutional [Transformer](Transformer.qmd) block leveraging a convolutional projection
	- shift, scale, and distortion invariance
	- dynamic [Attention](Attention.qmd) , global context, and better generalization
	- [ImageNet](ImageNet.qmd)
	- [Position Encoding](Position%20Encoding.qmd) , a crucial component in existing Vision Transformers, can be safely removed in our model
	- potential advantage for adaption
	- built-in local context structure introduced by convolutions, CvT no longer requires a position [embedding](Embedding.qmd)



