
---
categories: ['anchor']
---

- [1D-ALVINN.qmd](1D-ALVINN.qmd)
- [AudioSet classification.qmd](AudioSet%20classification.qmd)
- [AudioSet.qmd](AudioSet.qmd)
- [BUCC.qmd](BUCC.qmd)
- [Benchmark LLM.qmd](Benchmark%20LLM.qmd)
- [Billion Word.qmd](Billion%20Word.qmd)
- [BooksCorpus.qmd](BooksCorpus.qmd)
- [Broden.qmd](Broden.qmd)
- [CIFAR.qmd](CIFAR.qmd)
- [COCO.qmd](COCO.qmd)
- [CUB-200-2011 4.qmd](CUB-200-2011%204.qmd)
- [CUB-200-2011.qmd](CUB-200-2011.qmd)
- [Cityscapes.qmd](Cityscapes.qmd)
- [CommonCrawl.qmd](CommonCrawl.qmd)
- [DrawBench.qmd](DrawBench.qmd)
- [English Wikipedia.qmd](English%20Wikipedia.qmd)
- [Europarl-ST.qmd](Europarl-ST.qmd)
- [FGVC Aircraft.qmd](FGVC%20Aircraft.qmd)
- [FGVCx.qmd](FGVCx.qmd)
- [Fashion MNIST.qmd](Fashion%20MNIST.qmd)
- [Fine grained datasets.qmd](Fine%20grained%20datasets.qmd)
- [Fisher Spanish-English.qmd](Fisher%20Spanish-English.qmd)
- [Flickr30K.qmd](Flickr30K.qmd)
- [GLUE.qmd](GLUE.qmd)
- [GTA5.qmd](GTA5.qmd)
- [Google Conceptual Captions.qmd](Google%20Conceptual%20Captions.qmd)
- [Google voice search task.qmd](Google%20voice%20search%20task.qmd)
- [HMDB51.qmd](HMDB51.qmd)
- [IDRiD.qmd](IDRiD.qmd)
- [ILSVRC.qmd](ILSVRC.qmd)
- [IMDB.qmd](IMDB.qmd)
- [ISIC 2018.qmd](ISIC%202018.qmd)
- [KITTI.qmd](KITTI.qmd)
- [Kinetics.qmd](Kinetics.qmd)
- [Kvasir Dataset.qmd](Kvasir%20Dataset.qmd)
- [Labeled Faces in the Wild.qmd](Labeled%20Faces%20in%20the%20Wild.qmd)
- [LibriSpeech.qmd](LibriSpeech.qmd)
- [MILANNOTATIONS.qmd](MILANNOTATIONS.qmd)
- [MIT1003.qmd](MIT1003.qmd)
- [MIT300.qmd](MIT300.qmd)
- [MLDoc.qmd](MLDoc.qmd)
- [MMLU.qmd](MMLU.qmd)
- [MNIST.qmd](MNIST.qmd)
- [MSCOCO.qmd](MSCOCO.qmd)
- [MUSAN.qmd](MUSAN.qmd)
- [Moment in Time.qmd](Moment%20in%20Time.qmd)
- [NIST 2008 Speaker Recognition Evaluation dataset.qmd](NIST%202008%20Speaker%20Recognition%20Evaluation%20dataset.qmd)
- [NIST SRE 2016 Cantonese.qmd](NIST%20SRE%202016%20Cantonese.qmd)
- [NLVR2 3.qmd](NLVR2%203.qmd)
- [OSIE.qmd](OSIE.qmd)
- [PASCAL VOC.qmd](PASCAL%20VOC.qmd)
- [PASCAL-S.qmd](PASCAL-S.qmd)
- [People Art Dataset.qmd](People%20Art%20Dataset.qmd)
- [Picasso Dataset.qmd](Picasso%20Dataset.qmd)
- [Places.qmd](Places.qmd)
- [Places365.qmd](Places365.qmd)
- [PlantCLEF.qmd](PlantCLEF.qmd)
- [RACE.qmd](RACE.qmd)
- [SBU Captions.qmd](SBU%20Captions.qmd)
- [SQuAD.qmd](SQuAD.qmd)
- [STL-10.qmd](STL-10.qmd)
- [SUNCG.qmd](SUNCG.qmd)
- [SYNTHIA.qmd](SYNTHIA.qmd)
- [Salicon dataset.qmd](Salicon%20dataset.qmd)
- [SceneNet RGB-D.qmd](SceneNet%20RGB-D.qmd)
- [Shapes Dataset.qmd](Shapes%20Dataset.qmd)
- [Speakers in the Wild.qmd](Speakers%20in%20the%20Wild.qmd)
- [Stanford Dogs.qmd](Stanford%20Dogs.qmd)
- [Swichboard.qmd](Swichboard.qmd)
- [UCF101.qmd](UCF101.qmd)
- [VGGFace2 3.qmd](VGGFace2%203.qmd)
- [VQAv2 3.qmd](VQAv2%203.qmd)
- [Visual Commonsense Reasoning.qmd](Visual%20Commonsense%20Reasoning.qmd)
- [Visual Genome.qmd](Visual%20Genome.qmd)
- [WMT14.qmd](WMT14.qmd)
- [Wall Street Journal task.qmd](Wall%20Street%20Journal%20task.qmd)
- [XLSR.qmd](XLSR.qmd)
- [YFCC100M.qmd](YFCC100M.qmd)
- [iNaturalist.qmd](iNaturalist.qmd)
