---
title: Knowledge Base
categories: ['index']
date modified: Sunday, November 6th 2022, 2:28:46 pm
date created: Tuesday, July 26th 2022, 8:33:15 pm
listing:
  sort: "date desc"
  type: table
  categories: true
  sort-ui: true
  filter-ui: false
page-layout: full
title-block-banner: true
---

- ## Welcome!
- This is my little knowledge base
- If there is something you are looking for, just type it into the search bar
	- Of course, since this is not google, it is not a one stop shop
	- In essence, it will have something on things that I learn
- How to go about finding things?
	- Scroll the sidebar and pick something you like. Click the links inside it to go about. Choose your own adventure.
- Major topics (These index pages are auto generated and might have errors sometimes)
	- Quotes collected from a lot of places over the years [quotes](gen_quotes)
	- Technical
		- [Complete AI Pipeline](Complete%20AI%20Pipeline.qmd)
		- [AI Ethics](ethics.qmd)
		- [XAI](explainability.qmd)
		- [Deep Learning architectures](architecture.qmd)
		- [Loss Functions](loss.qmd)
		- [Datasets](dataset.qmd)
		- [Regularizing stuff](regularize.qmd)
		- [Robotics](robotics.qmd)
		- [Brain](brain.qmd)
		- [Visualization](visualization.qmd)
		- [Language](language.qmd)
		- [Medical](medical.qmd)
		- [Psychology](psychology.qmd)
		- [Cognitive Modelling](cognitivemodel)
	- Creative
		- [Composition](composition.qmd)
	- History
- ## Links
- [My Github](https://www.github.com/SubhadityaMukherjee)
- [Blogs](https://subhadityamukherjee.github.io/SubhadityaMukherjeegit/deeplearning.html)
- [Medium -> More blogs](https://msubhaditya.medium.com/)
- [My Linkedin](https://www.linkedin.com/in/subhaditya-mukherjee-a36883100)
- [My Art](https://www.instagram.com/aiexistentialart/)
- [Email](mailto:msubhaditya@gmail.com)
  
  #anchor
