
---
categories: ['anchor']
---

- [0-1 Loss.qmd](0-1%20Loss.qmd)
- [AUC-Borji.qmd](AUC-Borji.qmd)
- [AUC-Judd.qmd](AUC-Judd.qmd)
- [Absolute Error.qmd](Absolute%20Error.qmd)
- [Adversarial Loss.qmd](Adversarial%20Loss.qmd)
- [Akaike Information Criterion.qmd](Akaike%20Information%20Criterion.qmd)
- [Attention Alignment.qmd](Attention%20Alignment.qmd)
- [BCE with Logits.qmd](BCE%20with%20Logits.qmd)
- [BLEU.qmd](BLEU.qmd)
- [Bayesian Information Criterion.qmd](Bayesian%20Information%20Criterion.qmd)
- [Binary Cross Entropy.qmd](Binary%20Cross%20Entropy.qmd)
- [CTC.qmd](CTC.qmd)
- [Confusion Matrix.qmd](Confusion%20Matrix.qmd)
- [Contrastive Loss.qmd](Contrastive%20Loss.qmd)
- [Cosine Similarity.qmd](Cosine%20Similarity.qmd)
- [Cross Entropy.qmd](Cross%20Entropy.qmd)
- [Cycle Consistency Loss.qmd](Cycle%20Consistency%20Loss.qmd)
- [Dice Score.qmd](Dice%20Score.qmd)
- [Focal Loss.qmd](Focal%20Loss.qmd)
- [GE2E.qmd](GE2E.qmd)
- [Hinge Loss.qmd](Hinge%20Loss.qmd)
- [Huber.qmd](Huber.qmd)
- [ITM Loss.qmd](ITM%20Loss.qmd)
- [Identity Loss.qmd](Identity%20Loss.qmd)
- [Intra cluster variance.qmd](Intra%20cluster%20variance.qmd)
- [Jensen Shannon Divergence Consistency Loss.qmd](Jensen%20Shannon%20Divergence%20Consistency%20Loss.qmd)
- [KL Divergence.qmd](KL%20Divergence.qmd)
- [Log Likelihood Loss.qmd](Log%20Likelihood%20Loss.qmd)
- [LogCosh.qmd](LogCosh.qmd)
- [MAE.qmd](MAE.qmd)
- [MAPE.qmd](MAPE.qmd)
- [MSE.qmd](MSE.qmd)
- [MSLE.qmd](MSLE.qmd)
- [Mallows Cp Statistic.qmd](Mallows%20Cp%20Statistic.qmd)
- [Margin Ranking.qmd](Margin%20Ranking.qmd)
- [Max Margin Loss.qmd](Max%20Margin%20Loss.qmd)
- [Negative Log Likelihood.qmd](Negative%20Log%20Likelihood.qmd)
- [PatchGAN.qmd](PatchGAN.qmd)
- [Perplexity.qmd](Perplexity.qmd)
- [Poisson Loss.qmd](Poisson%20Loss.qmd)
- [Precision Recall Curve.qmd](Precision%20Recall%20Curve.qmd)
- [Precision.qmd](Precision.qmd)
- [Quadratic Loss.qmd](Quadratic%20Loss.qmd)
- [RAHP.qmd](RAHP.qmd)
- [ROC Curve.qmd](ROC%20Curve.qmd)
- [Recall.qmd](Recall.qmd)
- [Reconstruction loss.qmd](Reconstruction%20loss.qmd)
- [SDR.qmd](SDR.qmd)
- [SSR.qmd](SSR.qmd)
- [Sensitivity.qmd](Sensitivity.qmd)
- [Shuffled-AUC.qmd](Shuffled-AUC.qmd)
- [Sparse Dictionary Learning Loss.qmd](Sparse%20Dictionary%20Learning%20Loss.qmd)
- [Specificity.qmd](Specificity.qmd)
- [Squared Error.qmd](Squared%20Error.qmd)
- [Squared Hinge.qmd](Squared%20Hinge.qmd)
- [Triplet Loss.qmd](Triplet%20Loss.qmd)
- [inter-sentence coherence loss.qmd](inter-sentence%20coherence%20loss.qmd)
