---
toc: true
title: MILAN

categories: ['article']
date modified: Sunday, November 6th 2022, 5:17:22 pm
date created: Tuesday, July 26th 2022, 5:03:15 pm
---

# MILAN

  - [Natural Language Descriptions of Deep Visual Features](https://arxiv.org/abs/2201.11114)
  - Some neurons in deep networks specialize in recognizing highly specific perceptual, structural, or semantic [features](Features.qmd) of inputs
  - identifying neurons that respond to individual concept categories
  - richer characterization of neuron-level computation
  - mutual-information-guided linguistic annotation of neurons
  - generate open-ended, compositional, natural language descriptions of individual neurons in deep networks
  - generates a description by searching for a natural language string that maximizes pointwise mutual information with the image regions in which the neuron is active
  - [MILANNOTATIONS](MILANNOTATIONS.qmd)
  - fine-grained descriptions that capture categorical, relational, and logical structure in learned [features](Features.qmd)
  - characterizing the distribution and importance of neurons selective for attribute, category, and relational information in vision models.
  - auditing, surfacing neurons sensitive to protected categories like race and gender in models trained on datasets intended to obscure these [features](Features.qmd)
  - editing, improving robustness in an image classifier by deleting neurons sensitive to text [features](Features.qmd) spuriously correlated with class labels



