---
categories: ['temp']
date modified: Monday, October 10th 2022, 2:02:15 pm
date created: Tuesday, July 26th 2022, 8:33:15 pm
---

---

title: Swin Transformer

categories: ['temp']

---

# Swin [Transformer](Transformer.qmd)
- [Swin Transformer: Hierarchical Vision Transformer Using Shifted Windows](https://arxiv.org/abs/2103.14030)
	- [Vision Transformer](Vision%20Transformer.qmd)
	- general-purpose backbone for computer vision
	- hierarchical feature representation
	- linear computational complexity with respect to input image size
	- shifted window based [Self Attention](Self%20Attention.qmd)
	- address the challenges in adapting [Transformer](Transformer.qmd) from language to vision
	- limiting self-[attention](Attention.qmd) computation to non-overlapping local windows while also allowing for cross-window connection
	- flexibility to model at various scales
	- linear computational complexity with respect to image size
	- [ImageNet](ImageNet.qmd)
	- [COCO](COCO.qmd)
	- [ADE20K](ADE20K.qmd)
	- The hierarchical design and the shifted window approach also prove beneficial for all [Perception](Perception.qmd) [Architectures](Architectures).
	- Ratio of 1:1:3:1



