## Augmentation

### Methods
- [Attentive CutMix](Attentive%20CutMix.qmd) 
- [AttributeMix](AttributeMix)
- [AugMix](AugMix)
- [GridMask](GridMask)
- [Hide and Seek](Hide%20and%20Seek.qmd) 
- [Image Mixing and Deletion](Image%20Mixing%20and%20Deletion.qmd) 
- [Intra-Class Part Swapping](Intra-Class%20Part%20Swapping.qmd) 
- [Puzzle Mix](Puzzle%20Mix.qmd) 
- [KeepAugment](KeepAugment)
- [RICAP](RICAP)
- [RandAugment](RandAugment)
- [Random Distortion](Random%20Distortion.qmd) 
- [Random Erasing](Random%20Erasing.qmd) 
- [ReMix](ReMix)
- [ResizeMix](ResizeMix)
- [SMOTE](SMOTE)
- [SaliencyMix](SaliencyMix)
- [Sample Pairing](Sample%20Pairing.qmd) 
- [Visual Context Augmentation](Visual%20Context%20Augmentation.qmd) 
- [SmoothMix](SmoothMix)
- [SnapMix](SnapMix)
- [SpecAugment](SpecAugment)
- [Co-Mixup](Co-Mixup.qmd)
- [Cut and Mix](Cut%20and%20Mix.qmd) 
- [Data Augmentation via Latent Space Interpolation for Image Classification](Data%20Augmentation%20via%20Latent%20Space%20Interpolation%20for%20Image%20Classification.qmd) 
- [Data Augmentation with Curriculum Learning](Data%20Augmentation%20with%20Curriculum%20Learning.qmd) 

### Disadvantages

## [XAI](XAI.qmd)

### Methods
- [Adaptive Whitening Saliency](Adaptive%20Whitening%20Saliency.qmd) 
- [Bayesian Rule List](Bayesian%20Rule%20List.qmd) 
- [CAM](CAM)
- [Conductance](Conductance)
- [DeconvNet](DeconvNet)
- [Deep Inside Convolutional Networks](Deep%20Inside%20Convolutional%20Networks.qmd) 
- [Deep Visual Explanation](Deep%20Visual%20Explanation.qmd) 
- [DeepFool](DeepFool)
- [DeepLIFT](DeepLIFT)
- [Dynamic visual attention](Dynamic%20visual%20attention.qmd) 
- [Embedding Human Knowledge into Deep Neural Network via Attention Map](Embedding%20Human%20Knowledge%20into%20Deep%20Neural%20Network%20via%20Attention%20Map.qmd) 
- [Generalizing Adversarial Explanations with Grad-CAM](Generalizing%20Adversarial%20Explanations%20with%20Grad-CAM.qmd) 
- [Graph-based visual saliency](Graph-based%20visual%20saliency.qmd) 
- [Guided BackProp](Guided%20BackProp.qmd) 
- [Guided GradCAM](Guided%20GradCAM.qmd) 
- [Influence of image classification accuracy on saliency map estimation](Influence%20of%20image%20classification%20accuracy%20on%20saliency%20map%20estimation.qmd) 
- [Integrated Gradients](Integrated%20Gradients.qmd) 
- [Interpretation of Neural networks is fragile](Interpretation%20of%20Neural%20networks%20is%20fragile.qmd) 
- [Noise Tunnel](Noise%20Tunnel.qmd) 
- [On the overlap between Grad-CAM saliency maps and explainable visual features in skin cancer images](On%20the%20overlap%20between%20Grad-CAM%20saliency%20maps%20and%20explainable%20visual%20features%20in%20skin%20cancer%20images.qmd) 
- [RISE](RISE)
- [Real Time Image Saliency for Black Box Classifiers](Real%20Time%20Image%20Saliency%20for%20Black%20Box%20Classifiers.qmd) 
- [SAM-ResNet](SAM-ResNet)
- [SDR](SDR)
- [SP-LIME](SP-LIME)
- [Salience Map](Salience%20Map.qmd) 
- [Smooth-Grad](Smooth-Grad)
- [SmoothGrad Square](SmoothGrad%20Square.qmd) 
- [Summit](Summit)
- [VarGrad](VarGrad)
- [ScoreCAM](ScoreCAM.qmd)

### Disadvantages
- [Beware of Inmates Running the Asylum](Beware%20of%20Inmates%20Running%20the%20Asylum.qmd) 
- [The Unreliability of Saliency Methods](The%20Unreliability%20of%20Saliency%20Methods.qmd) 


## Architectures
- [Res Net](Res%20Net.qmd) 
- [Vision Transformer](Vision%20Transformer.qmd) 
- [ConvNeXt](ConvNeXt)
- [Mobile Net](Mobile%20Net.qmd) 
- [Vgg](Vgg)
- [Xception](Xception)



