
---
categories: ['anchor']
---

- [Algebra Cognitive Tutor.qmd](Algebra%20Cognitive%20Tutor.qmd)
- [Andes.qmd](Andes.qmd)
- [AutoTutor.qmd](AutoTutor.qmd)
- [Coarse-grained assessment.qmd](Coarse-grained%20assessment.qmd)
- [Collaborative Recommender.qmd](Collaborative%20Recommender.qmd)
- [Content Based Recommender.qmd](Content%20Based%20Recommender.qmd)
- [DT Tutor.qmd](DT%20Tutor.qmd)
- [Declarative memory.qmd](Declarative%20memory.qmd)
- [Effects of Contextual Cues on Inferring and Remembering Meanings of New Word.qmd](Effects%20of%20Contextual%20Cues%20on%20Inferring%20and%20Remembering%20Meanings%20of%20New%20Word.qmd)
- [Extensions to SlimStampen.qmd](Extensions%20to%20SlimStampen.qmd)
- [Eye Tracking.qmd](Eye%20Tracking.qmd)
- [Filter Bubble Problem.qmd](Filter%20Bubble%20Problem.qmd)
- [Final Paper User Models.qmd](Final%20Paper%20User%20Models.qmd)
- [Fine Grained assesment.qmd](Fine%20Grained%20assesment.qmd)
- [GOMS.qmd](GOMS.qmd)
- [Game Based Learning.qmd](Game%20Based%20Learning.qmd)
- [Gamification.qmd](Gamification.qmd)
- [Gaze position.qmd](Gaze%20position.qmd)
- [Grey sheep problem.qmd](Grey%20sheep%20problem.qmd)
- [Group Modeling Approach.qmd](Group%20Modeling%20Approach.qmd)
- [Help Abuse.qmd](Help%20Abuse.qmd)
- [Help Refusal.qmd](Help%20Refusal.qmd)
- [IRT.qmd](IRT.qmd)
- [Ideas for Fact Learning.qmd](Ideas%20for%20Fact%20Learning.qmd)
- [Individual Modeling.qmd](Individual%20Modeling.qmd)
- [Knowledge Component.qmd](Knowledge%20Component.qmd)
- [Latent Semantic Analysis.qmd](Latent%20Semantic%20Analysis.qmd)
- [Learning Event.qmd](Learning%20Event.qmd)
- [Learning L2 German Vocabulary Through Reading.qmd](Learning%20L2%20German%20Vocabulary%20Through%20Reading.qmd)
- [Macroadaptation.qmd](Macroadaptation.qmd)
- [Mastery learning.qmd](Mastery%20learning.qmd)
- [Modeling Driver Behavior with Cognitive Architecture.qmd](Modeling%20Driver%20Behavior%20with%20Cognitive%20Architecture.qmd)
- [Modeling Transfer.qmd](Modeling%20Transfer.qmd)
- [Predicting Student learning Curve.qmd](Predicting%20Student%20learning%20Curve.qmd)
- [Pupil Dilation.qmd](Pupil%20Dilation.qmd)
- [Ramp up problem.qmd](Ramp%20up%20problem.qmd)
- [Rational inference.qmd](Rational%20inference.qmd)
- [Recommender System.qmd](Recommender%20System.qmd)
- [SQL-Tutor.qmd](SQL-Tutor.qmd)
- [Satisficing Heuristic.qmd](Satisficing%20Heuristic.qmd)
- [Second Language Vocabulary Learning , The role of context  versus translation.qmd](Second%20Language%20Vocabulary%20Learning%20,%20The%20role%20of%20context%20%20versus%20translation.qmd)
- [Serious Games.qmd](Serious%20Games.qmd)
- [Sherlock.qmd](Sherlock.qmd)
- [SlimStampen.qmd](SlimStampen.qmd)
- [Steve.qmd](Steve.qmd)
- [The Behavior of Tutoring Systems.qmd](The%20Behavior%20of%20Tutoring%20Systems.qmd)
- [The Effect of Three Consecutive Context Sentences on EFL Vocabulary-Learning.qmd](The%20Effect%20of%20Three%20Consecutive%20Context%20Sentences%20on%20EFL%20Vocabulary-Learning.qmd)
- [Tutor.qmd](Tutor.qmd)
- [plan recognition problem.qmd](plan%20recognition%20problem.qmd)
